### ISSUE TITLE
Error when running docker-compser up -d

### ISSUE THREAD

**Issue by sanojsilva** [chrisleekr/yii2-angular-boilerplate#14]
I Get the following error after when i run docker-compose up -d command. I'm on windows.

Composer (version 1.6.5) successfully installed to: /usr/local/bin/composer.phar
Use it: php /usr/local/bin/composer.phar

': No such file or directory
Service 'api' failed to build: The command '/bin/sh -c curl -sS https://getcomposer.org/installer | php --         --filename=composer.phar         --install-dir=/usr/local/bin &&     composer global require --optimize-autoloader         "fxp/composer-asset-plugin:${VERSION_COMPOSER_ASSET_PLUGIN}"         "hirak/prestissimo:${VERSION_PRESTISSIMO_PLUGIN}" &&     composer global dumpautoload --optimize &&     composer clear-cache' returned a non-zero code: 127

**Comment by sanojsilva** [comment]
@chrisleekr I think it can't find the composer installation path

**Comment by chrisleekr** [comment]
Have you modified `Dockerfile` for api? 

I could not reproduce the issue. Please provide steps to get that issue.

**Comment by chrisleekr** [comment]
@ArunaSanjeewa What error have you got and in what environment?

**Comment by ArunaSanjeewa** [comment]
PC OS - Windows 10.
Docker container type -Linux.
Error - 
Composer (version 1.6.5) successfully installed to: /usr/local/bin/composer.phar
Use it: php /usr/local/bin/composer.phar
': No such file or directory
Service 'api' failed to build: The command '/bin/sh -c curl -sS https://getcomposer.org/installer | php -- --filename=composer.phar --install-dir=/usr/local/bin && composer global require --optimize-autoloader "fxp/composer-asset-plugin:${VERSION_COMPOSER_ASSET_PLUGIN}" "hirak/prestissimo:${VERSION_PRESTISSIMO_PLUGIN}" && composer global dumpautoload --optimize && composer clear-cache' returned a non-zero code: 127

**Comment by chrisleekr** [comment]
Unfortunately, I don't have Windows machine in the home. I only have linux and Mac. :( 

If anyone who has Windows machine, please help to fix this issue.

**Comment by rdobrynin** [comment]
Same problem! Can't fix this issue

**Comment by omidmm** [comment]
thanks @chrisleekr for this project
solution for  this problem :  use powershell  on linux container

**Comment by chrisleekr** [comment]
@omidmm 

Thank you so much. I will let others know about this.

**Comment by desaikalpesh34** [comment]
same issue here if any one help please comment solution
http://prntscr.com/lyzpaa

**Comment by omidmm** [comment]
hi @desaikalpesh34 ,Good time
if you need project only for review code and learning methods of work,
you can set Separate project , mean : 
download project api to www directory of wamp or xamp, 
and composer update , then create database and migrate, set config file ,
then in frontend and backend directory type ng serve --open 
change evireoment file to set api url , 
If you need more guidance , type here , or send to my email :omidmm16@gmail.com
