### ISSUE TITLE
ERROR: Service 'frontend' failed to build: Error parsing reference:

### ISSUE THREAD

**Issue by smanikandan-btech** [chrisleekr/yii2-angular-boilerplate#16]
![screenshot from 2018-09-05 23-20-39](https://user-images.githubusercontent.com/6849661/45111415-8d47bb80-b162-11e8-9688-08020d0d568b.png)

I'm getting this error. Please help to resolve.

**Comment by chrisleekr** [comment]
@smanikandan-btech what version of `docker-compose` are you using?

**Comment by smanikandan-btech** [comment]
@chrisleekr  I'm using docker-compose version 1.22.0

**Comment by chrisleekr** [comment]
Hm, strange. 

I am currently using
`Docker version 18.06.1-ce, build e68fc7a`
and 
`dockerdocker-compose version 1.22.0, build f46880f`

I just cloned the repo and tried to build again, it worked.

Are you using latest docker? Could you try with latest docker?

**Comment by smanikandan-btech** [comment]
@chrisleekr Thanks for your suggestion. I will try and let you know.

**Comment by chrisleekr** [comment]
@smanikandan-btech have you fixed the issue? If yes, I will close the issue.

**Comment by smanikandan-btech** [comment]
@chrisleekr  No. I didn't fixed. I have no idea. Can't get time.
