### ISSUE TITLE
ERROR: Service 'api' failed to build:

### ISSUE THREAD

**Issue by rohitsuthar** [chrisleekr/yii2-angular-boilerplate#17]
![failed01](https://user-images.githubusercontent.com/6672385/46065799-af948e00-c190-11e8-9cd0-8ebe502de688.png)

I'm getting the below error, please help me to resolve this -

> ERROR: Service 'api' failed to build: The command '/bin/sh -c curl -sS https://getcomposer.org/installer | php --         --filename=composer.phar         --install-dir=/usr/local/bin &&     composer global require --optimize-autoloader         "fxp/composer-asset-plugin:${VERSION_COMPOSER_ASSET_PLUGIN}"         "hirak/prestissimo:${VERSION_PRESTISSIMO_PLUGIN}" &&     composer global dumpautoload --optimize &&     composer clear-cache' returned a non-zero code: 127

**Comment by chrisleekr** [comment]
Hi @rohitsuthar 

Unfortunately, I do not have Windows machine at home. 
So it is hard me to find the solution for you. 

I think others also have same issue with you. 
If you can find the solution, please share to help others as well.

**Comment by omidmm** [comment]
hi , my friends
in windows for docker commands use powershell

**Comment by thomassb** [comment]
Seems like it can be resolved by the
`git config --global core.autocrlf false` command
before `git clone` ... and `docker-compose build`
