### ISSUE TITLE
Please Add PHPmyadmin

### ISSUE THREAD

**Issue by agsachdev** [chrisleekr/yii2-angular-boilerplate#20]
Please Add PHPmyadmin

**Comment by agsachdev** [comment]
I need PHPMyAdmin :-( Could please add in docker

**Comment by srebrny** [comment]
`phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - internal
`

Just add it into service: section
