### ISSUE TITLE
Need brief explain about docker  and nginx

### ISSUE THREAD

**Issue by rspsuresh** [chrisleekr/yii2-angular-boilerplate#24]

**Comment by chrisleekr** [comment]
Hi, 

I am not sure what you want an explanation.

**Comment by chrisleekr** [comment]
If you meant generic docker information, please google it.

**Comment by rspsuresh** [comment]
> Hi,
> 
> I am not sure what you want an explanation.

any option is there  for install ,without using docker for this pack
