### ISSUE TITLE
BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

### ISSUE THREAD

**Issue by rspsuresh** [chrisleekr/yii2-angular-boilerplate#27]
In my angular 7 i have face error like this.after lot of R&D code side all are correct.while i replace old node_modules to current node_modules.its working fine.Really i cant find exact error.please help me as soon as possible

**Comment by chrisleekr** [comment]
Not sure what you want from this repo. Please google it. Thans.
