### ISSUE TITLE
pageSizeLimit

### ISSUE THREAD

**Issue by tsvetiligo** [chrisleekr/yii2-angular-boilerplate#35]
In UserSearch model:
`'pageSizeLimit' => [10, 50, 100]`
[10, 50, 100] - wrong value and pageSizeLimit don't work at all, if I set per_page=0 ActiveDataProvider show ALL rows
From Yii2 manual:
> $pageSizeLimit public property
> The page size limits. The first array element stands for the minimal page size, and the second the maximal page size. If this is false, it means $pageSize should always return the value of $defaultPageSize.
> public array|false $pageSizeLimit = [1, 50]

**Comment by chrisleekr** [comment]
Happy to get PR from you. :)

**Comment by chrisleekr** [comment]
Fixed with https://github.com/chrisleekr/yii2-angular-boilerplate/pull/39
