### ISSUE TITLE
API Bad Request

### ISSUE THREAD

**Issue by mohdrona9393** [chrisleekr/yii2-angular-boilerplate#47]
![image](https://user-images.githubusercontent.com/35664538/95688481-061c7a00-0c3d-11eb-9c3a-ad3dedba037e.png)

{"name":"Bad Request","message":"The system could not process your request. Please check and try again.","code":0,"status":400,"type":"yii\\web\\BadRequestHttpException"}

 current php 7.2 

i need tutorial video how this project working properly on localhost

@chrisleekr please advice us,

**Comment by chrisleekr** [comment]
@mohdrona9393 I have tried and it seems working as expected. Can you docker logs api and see what the error is?

**Comment by chrisleekr** [comment]
Didn't hear from you a long time. Close the issue. If you still have an issue, please reopen.
